server:
  port: 4006
spring:
  application:
    name: livegoods-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: banner
          uri: lb://livegoods-banner
          predicates:
            - Path=/banner
        - id: hotproduct
          uri: lb://livegoods-hotProduct
          predicates:
            - Path=/hotProduct
            - Query=city # 请求中必须包含city参数，参数内容不限
        - id: recommendation
          uri: lb://livegoods-recommendation
          predicates:
            - Path=/recommendation
            - Query=city
        - id: search
          uri: lb://livegoods-search
          predicates:
            - Path=/search
            - Query=city
            - Query=page
            - Query=content
        - id: details
          uri: lb://livegoods-details
          predicates:
            - Path=/details
            - Query=id
        - id: comment
          uri: lb://livegoods-comment
          predicates:
            - Path=/comment
            - Query=id
            - Query=page
        - id: buytime
          uri: lb://livegoods-buytime
          predicates:
            - Path=/buytime
            - Query=id
        - id: sendyzm
          uri: lb://livegoods-login
          predicates:
            - Path=/sendyzm
        - id: login
          uri: lb://livegoods-login
          predicates:
            - Path=/login
        - id: buyaction
          uri: lb://livegoods-buyaction
          predicates:
            - Path=/buyaction
        - id: order
          uri: lb://livegoods-order
          predicates:
            - Path=/order
            - Query=user
        - id: feelback
          uri: lb://livegoods-comment
          predicates:
            - Path=/feelback
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.3:8761/eureka