server:
  port: 4006
spring:
  application:
    name: livegoods-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: banner
          uri: lb://livegoods-banner
          predicates:
            - Path=/banner
        - id: hotproduct
          uri: lb://livegoods-hotProduct
          predicates:
            - Path=/hotProduct
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.3:8761/eureka