spring:
  application:
    name: livegoods-hotProduct
  profiles:
    active: mongo

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.3:8761/eureka/
  instance:
    prefer-ip-address: true
