#livegoods:
#  search:
#    init:
#      enabled: true # 配置是否需要初始化索引，创建和设置映射。默认为false
spring:
  profiles:
    active: mongo
  application:
    name: livegoods-search
  elasticsearch:
    uris: 127.0.0.1:9200
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.3:8761/eureka/
  instance:
    prefer-ip-address: true
