server:
  port: 9008
spring:
  application:
    name: livegoods-buyaction
  profiles:
    active: buyQueue,itemCacheName,redis,rabbitmq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
